seed: ${generate_random_seed:}

data_dir: ${hydra:runtime.cwd}/data

outputs_dir: ${hydra:runtime.cwd}/outputs

outputs_subdir: dev

job_subdir: dev

hydra:
  run:
    dir: outputs/${outputs_subdir}/${hydra.job.name}/${job_subdir}/${now:%Y-%m-%d_%H-%M-%S-%f}
  job:
    chdir: true
  verbose: false

wandb:
  project: operator-cow
  dir: ${hydra:runtime.cwd}/outputs
  mode: online
  anonymous: allow
  tags:
    - development

data:
  path: /data/path/placeholder
  batch_size: 8

model:
  name: AE
  layers: [100, 64, 32, 16]
  model_save_path: placeholder

training:
  epochs: 1500
  grad_clip: 1000.0


optimizer:
  lr: 0.001
  weight_decay: 0.00005
  beta1: 0.9
  beta2: 0.999
