
program: Inverse_sweep.py

method: grid

metric:
  goal: minimize
  name: L2s

parameters:
  lambda_mass:
   values: [100, 1000, 10000]
  lambda_pressure:
    values: [0.00001, 0.0000001, 0.00000001]
  lambda_mes:
    values: [100, 10, 1]
  lambda_a0:
    values: [1000]
  max_iters:
    values: [3000]
  eps:
    values: [0.000006]
  batch_size:
    values: [18]
  lr:
    values: [0.1, 0.01, 0.001]
  log_every: 
    values: [100]
  path_to_csv:
    values: [/home/wssk-ptw/Operator/operator-cow/src/operatorcow/inverse/ROM/ROM_DATA/inverse_network_ROM.csv]
  name:
    values: [GNOT]
  trunk_size:
    values: [52]
  branch_sizes:
    values: [[3,3]]
  output_size:
    values: [3]
  space_dim:
    values: [2]
  n_layers:
    values: [3]
  n_hidden:
    values: [96]
  n_head:
    values: [8]
  n_experts:
    values: [4]
  n_inner:
    values: [4]
  mlp_layers:
    values: [4]
  attn_type:
    values: [linear]
  act:
    values: [gelu]
  ffn_dropout:
    values: [0.0]
  attn_dropout:
    values: [0.0]
  horiz_fourier_dim:
    values: [0]
  AE_weights_path:
    values: [/data/path/placeholder]
  surrogate_weights_path:
    values: [/home/wssk-ptw/Operator/Model_archive/GNOT_FINAL.pt]
  VANO_weights_path:
    values: [/home/wssk-ptw/Operator/Model_archive/VANO_FINAL.pt]
  layers_encoder:
    values: [[111, 256, 256, 256, 32]]
  layers_decoder:
    values: [[27, 256, 256, 256, 100]]
  latent_dim:
    values: [16]
  data_path:
    values: [/home/wssk-ptw/Operator/COW_DATASET/VALIDATION/]
  joints_path:
    values: [/home/wssk-ptw/Operator/operator-cow/data/joints.csv]


  

