seed: ${generate_random_seed:}

data_dir: ${hydra:runtime.cwd}/data

outputs_dir: ${hydra:runtime.cwd}/outputs

outputs_subdir: dev

job_subdir: dev

hydra:
  run:
    dir: outputs/${outputs_subdir}/${hydra.job.name}/${job_subdir}/${now:%Y-%m-%d_%H-%M-%S-%f}
  job:
    chdir: true
  verbose: false

wandb:
  project: operator-cow
  dir: ${hydra:runtime.cwd}/outputs
  mode: online
  anonymous: allow
  tags:
    - development

data:
  path: /data/path/placeholder
  batch_size: 8

model:
  name: VANO
  layers_encoder: [111, 64, 32, 32]
  layers_decoder: [27, 32, 64, 100]
  model_save_path: placeholder
  latent_dim: 16

training:
  epochs: 500
  grad_clip: 1000.0
  S: 4
  beta: 0.001


optimizer:
  lr: 0.001
  weight_decay: 0.00005
  beta1: 0.9
  beta2: 0.999
