seed: ${generate_random_seed:}

data_dir: ${hydra:runtime.cwd}/data

outputs_dir: ${hydra:runtime.cwd}/outputs

outputs_subdir: dev

job_subdir: dev

hydra:
  run:
    dir: outputs/${outputs_subdir}/${hydra.job.name}/${job_subdir}/${now:%Y-%m-%d_%H-%M-%S-%f}
  job:
    chdir: true
  verbose: false

wandb:
  project: operator-cow
  dir: ${hydra:runtime.cwd}/outputs
  mode: online
  anonymous: allow
  tags:
    - development
data:
  path_train: /home/wssk-ptw/Operator/COW_DATASET_WRO_1_PI/GNOT_train_BIG_DATASET.npy
  path_test: /home/wssk-ptw/Operator/COW_DATASET_WRO_1_PI/GNOT_test_BIG_DATASET.npy
  batch_size: 32

model:
  name: VANO
  layers_encoder: [111, 256, 256, 256, 32]
  layers_decoder: [27, 256, 256, 256, 100]
  model_save_path: /home/wssk-ptw/Operator/operator-cow/data/checkpoints
  latent_dim: 16

training:
  epochs: 500
  grad_clip: 1000.0
  S: 16
  beta: 1


optimizer:
  lr: 0.0001
  weight_decay: 0.00005
  beta1: 0.9
  beta2: 0.999
